export const PERSONS_DATA_REQUEST = 'PERSONS_DATA_REQUEST';
export type PERSONS_DATA_REQUEST = typeof PERSONS_DATA_REQUEST;

export const PERSONS_DATA_SUCCESS = 'PERSONS_DATA_SUCCESS';
export type PERSONS_DATA_SUCCESS = typeof PERSONS_DATA_SUCCESS;

export const PERSONS_DATA_FAILURE = 'PERSONS_DATA_FAILURE';
export type PERSONS_DATA_FAILURE = typeof PERSONS_DATA_FAILURE;

export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export type ADD_FAVOURITE = typeof ADD_FAVOURITE;

export const DELETE_FAVOURITE = 'DELETE_FAVOURITE';
export type DELETE_FAVOURITE = typeof DELETE_FAVOURITE;
